const img = (seed) => `https://picsum.photos/seed/${seed}/1200/800`;

export const DEMO_LISTINGS = [
  {
    id: "demo-listing-west-campus-studio",
    title: "Sunny Studio 2 Blocks from the Drag",
    location: "West Campus, Austin",
    address: "2200 Nueces St, Austin, TX 78705",
    dates: "May 15, 2026 - Aug 15, 2026",
    startDate: "2026-05-15",
    endDate: "2026-08-15",
    term: "summer",
    features: ["cleanliness", "security", "communication"],
    price: 1050,
    monthlyRent: 1050,
    priceUnit: "per month",
    desc: "Full studio in a gated high-rise, subletting for the summer while I'm on a research internship. In-unit washer/dryer, fast fiber internet already set up, and a rooftop pool. Walk to Jester, Gregory Gym, and the Drag in under 10 minutes.",
    postedBy: "Maya Patel",
    posterEmail: "maya.demo@example.com",
    phone: "(512) 555-0142",
    photos: [img("ch-west-campus-studio-1"), img("ch-west-campus-studio-2")],
    ownerUid: "demo-maya",
    posterUsername: "mayapatel",
    status: "approved",
    underReview: false,
    demo: true,
  },
  {
    id: "demo-listing-north-campus-room",
    title: "Private Room in Quiet North Campus Duplex",
    location: "North Campus, Austin",
    address: "705 W 30th St, Austin, TX 78705",
    dates: "Aug 20, 2026 - Dec 20, 2026",
    startDate: "2026-08-20",
    endDate: "2026-12-20",
    term: "winter",
    features: ["cleanliness", "maintenance", "communication"],
    price: 775,
    monthlyRent: 775,
    priceUnit: "per month",
    desc: "Subletting my room in a 3-bed duplex for the fall semester while I'm abroad. Two easygoing roommates, both grad students. Shared backyard, dishwasher, and off-street parking. Ten-minute walk to Speedway and the PCL.",
    postedBy: "Jordan Lee",
    posterEmail: "jordan.demo@example.com",
    phone: "(512) 555-0198",
    photos: [img("ch-north-campus-room-1"), img("ch-north-campus-room-2")],
    ownerUid: "demo-jordan",
    posterUsername: "jordanlee",
    status: "approved",
    underReview: false,
    demo: true,
  },
  {
    id: "demo-listing-hyde-park-house",
    title: "Bright Room in Craftsman House, Hyde Park",
    location: "Hyde Park, Austin",
    address: "4210 Avenue B, Austin, TX 78751",
    dates: "Jan 5, 2027 - May 5, 2027",
    startDate: "2027-01-05",
    endDate: "2027-05-05",
    term: "winter",
    features: ["cheap", "communication", "security"],
    price: 690,
    monthlyRent: 690,
    priceUnit: "per month",
    desc: "Subletting for spring semester while I'm on a co-op. Historic craftsman house split between four students, big shared kitchen, front porch, and a short bike ride to campus along Duval. Utilities and lawn care included in rent.",
    postedBy: "Alex Nguyen",
    posterEmail: "alex.demo@example.com",
    phone: "(512) 555-0173",
    photos: [img("ch-hyde-park-house-1"), img("ch-hyde-park-house-2")],
    ownerUid: "demo-alex",
    posterUsername: "alexnguyen",
    status: "approved",
    underReview: false,
    demo: true,
  },
  {
    id: "demo-listing-riverside-1br",
    title: "1BR Apartment Near Lady Bird Lake Trail",
    location: "Riverside, Austin",
    address: "2400 Riverside Dr, Austin, TX 78741",
    dates: "May 20, 2026 - Aug 10, 2026",
    startDate: "2026-05-20",
    endDate: "2026-08-10",
    term: "summer",
    features: ["cleanliness", "cheap", "maintenance"],
    price: 950,
    monthlyRent: 950,
    priceUnit: "per month",
    desc: "Whole 1-bedroom apartment available for the summer while I'm home for a rotation. On the free UT shuttle route, pool and gym in the complex, and a two-minute walk to the hike-and-bike trail. Great for anyone doing a summer internship downtown.",
    postedBy: "Sofia Ramirez",
    posterEmail: "sofia.demo@example.com",
    phone: "(512) 555-0164",
    photos: [img("ch-riverside-1br-1"), img("ch-riverside-1br-2")],
    ownerUid: "demo-sofia",
    posterUsername: "sofiaramirez",
    status: "approved",
    underReview: false,
    demo: true,
  },
  {
    id: "demo-listing-west-campus-shared",
    title: "Shared Room, 3-Week Winter Break Sublet",
    location: "West Campus, Austin",
    address: "2606 Rio Grande St, Austin, TX 78705",
    dates: "Dec 12, 2026 - Jan 2, 2027",
    startDate: "2026-12-12",
    endDate: "2027-01-02",
    term: "weeks",
    features: ["cheap", "security"],
    price: 350,
    monthlyRent: 350,
    priceUnit: "total",
    desc: "Short winter-break sublet in a high-rise unit while I'm home for the holidays. Great option for someone doing a short internship or staying in town over break. Keyed elevator, package room, and study lounge on-site.",
    postedBy: "Maya Patel",
    posterEmail: "maya.demo@example.com",
    phone: "(512) 555-0142",
    photos: [img("ch-west-campus-shared-1")],
    ownerUid: "demo-maya",
    posterUsername: "mayapatel",
    status: "approved",
    underReview: false,
    demo: true,
  },
  {
    id: "demo-listing-north-campus-summer",
    title: "Room in North Campus House, Flexible Summer Dates",
    location: "North Campus, Austin",
    address: "2911 Duval St, Austin, TX 78705",
    dates: "Jun 1, 2026 - Aug 20, 2026",
    startDate: "2026-06-01",
    endDate: "2026-08-20",
    term: "summer",
    features: ["communication", "maintenance", "cheap"],
    price: 700,
    monthlyRent: 700,
    priceUnit: "per month",
    desc: "One room open in a 4-person house for the summer, flexible on exact move-in/move-out within the window. Central AC, fenced yard, and street parking. Easy walk to the Duval Street shuttle stop.",
    postedBy: "Jordan Lee",
    posterEmail: "jordan.demo@example.com",
    phone: "(512) 555-0198",
    photos: [img("ch-north-campus-summer-1")],
    ownerUid: "demo-jordan",
    posterUsername: "jordanlee",
    status: "approved",
    underReview: false,
    demo: true,
  },
];

export function mergeDemoListings(listings) {
  const seen = new Set(listings.map((listing) => listing.id));
  return [...listings, ...DEMO_LISTINGS.filter((listing) => !seen.has(listing.id))];
}

export function findDemoListing(id) {
  return DEMO_LISTINGS.find((listing) => String(listing.id) === String(id));
}
