const img = (seed) => `https://picsum.photos/seed/${seed}/1200/800`;

// Curated sample sublets so the board looks alive during demos. These are
// merged into getListings() at read time and never written to Firestore.
// Hosts map to the demo profiles in demoProfiles.js so host links resolve.
export const DEMO_LISTINGS = [
  {
    id: "demo-2026-westcampus-highrise",
    title: "Furnished Studio in West Campus High-Rise",
    location: "West Campus, Austin",
    address: "2400 Nueces St, Austin, TX 78705",
    dates: "May 18, 2026 - Aug 16, 2026",
    startDate: "2026-05-18",
    endDate: "2026-08-16",
    term: "summer",
    features: ["cleanliness", "security", "communication"],
    price: 1195,
    monthlyRent: 1195,
    priceUnit: "per month",
    desc: "Fully furnished studio in a gated high-rise two blocks from the Drag. In-unit washer/dryer, fiber internet included, rooftop pool, and a 24/7 front desk. Subletting while I'm away for a summer internship. Walk to Jester, the PCL, and Gregory Gym in under 10 minutes.",
    postedBy: "Maya Patel",
    posterEmail: "maya.demo@example.com",
    phone: "(512) 555-0142",
    photos: [img("ch-westcampus-highrise-a"), img("ch-westcampus-highrise-b")],
    ownerUid: "demo-maya",
    posterUsername: "mayapatel",
    status: "approved",
    underReview: false,
    demo: true,
  },
  {
    id: "demo-2026-northcampus-duplex",
    title: "Private Room in Quiet North Campus Duplex",
    location: "North Campus, Austin",
    address: "705 W 30th St, Austin, TX 78705",
    dates: "Aug 20, 2026 - Dec 20, 2026",
    startDate: "2026-08-20",
    endDate: "2026-12-20",
    term: "winter",
    features: ["cleanliness", "maintenance", "communication"],
    price: 815,
    monthlyRent: 815,
    priceUnit: "per month",
    desc: "Private furnished room in a 3-bed duplex for the fall semester while I study abroad. Two easygoing grad-student roommates, shared backyard, dishwasher, and off-street parking. Ten-minute walk to Speedway and the shuttle.",
    postedBy: "Jordan Lee",
    posterEmail: "jordan.demo@example.com",
    phone: "(512) 555-0198",
    photos: [img("ch-northcampus-duplex-a"), img("ch-northcampus-duplex-b")],
    ownerUid: "demo-jordan",
    posterUsername: "jordanlee",
    status: "approved",
    underReview: false,
    demo: true,
  },
  {
    id: "demo-2027-hydepark-craftsman",
    title: "Bright Room in Historic Hyde Park Craftsman",
    location: "Hyde Park, Austin",
    address: "4210 Avenue B, Austin, TX 78751",
    dates: "Jan 5, 2027 - May 5, 2027",
    startDate: "2027-01-05",
    endDate: "2027-05-05",
    term: "winter",
    features: ["cheap", "communication", "security"],
    price: 720,
    monthlyRent: 720,
    priceUnit: "per month",
    desc: "Spring-semester sublet in a historic craftsman split between four students. Big shared kitchen, front porch, and a quick bike ride to campus along Duval. Utilities, Wi-Fi, and lawn care included in rent.",
    postedBy: "Alex Nguyen",
    posterEmail: "alex.demo@example.com",
    phone: "(512) 555-0173",
    photos: [img("ch-hydepark-craftsman-a"), img("ch-hydepark-craftsman-b")],
    ownerUid: "demo-alex",
    posterUsername: "alexnguyen",
    status: "approved",
    underReview: false,
    demo: true,
  },
  {
    id: "demo-2026-riverside-1br",
    title: "Full 1BR Apartment Near Lady Bird Lake",
    location: "Riverside, Austin",
    address: "2400 E Riverside Dr, Austin, TX 78741",
    dates: "May 20, 2026 - Aug 10, 2026",
    startDate: "2026-05-20",
    endDate: "2026-08-10",
    term: "summer",
    features: ["cleanliness", "cheap", "maintenance"],
    price: 980,
    monthlyRent: 980,
    priceUnit: "per month",
    desc: "Whole one-bedroom apartment available for the summer while I'm home for a rotation. On the free UT shuttle route, pool and gym on-site, and a two-minute walk to the hike-and-bike trail. Ideal for a summer internship downtown.",
    postedBy: "Sofia Ramirez",
    posterEmail: "sofia.demo@example.com",
    phone: "(512) 555-0164",
    photos: [img("ch-riverside-1br-a"), img("ch-riverside-1br-b")],
    ownerUid: "demo-sofia",
    posterUsername: "sofiaramirez",
    status: "approved",
    underReview: false,
    demo: true,
  },
  {
    id: "demo-2026-westcampus-winterbreak",
    title: "Shared Room — 3-Week Winter Break Sublet",
    location: "West Campus, Austin",
    address: "2606 Rio Grande St, Austin, TX 78705",
    dates: "Dec 12, 2026 - Jan 2, 2027",
    startDate: "2026-12-12",
    endDate: "2027-01-02",
    term: "weeks",
    features: ["cheap", "security"],
    price: 380,
    monthlyRent: 380,
    priceUnit: "total",
    desc: "Short winter-break sublet in a West Campus high-rise while I'm home for the holidays. Perfect for a short internship or staying in town over break. Keyed elevator, package room, and a study lounge on-site.",
    postedBy: "Maya Patel",
    posterEmail: "maya.demo@example.com",
    phone: "(512) 555-0142",
    photos: [img("ch-westcampus-winterbreak-a")],
    ownerUid: "demo-maya",
    posterUsername: "mayapatel",
    status: "approved",
    underReview: false,
    demo: true,
  },
  {
    id: "demo-2026-northloop-bungalow",
    title: "Cozy Room in North Loop Bungalow",
    location: "North Loop, Austin",
    address: "5309 Avenue F, Austin, TX 78751",
    dates: "Jun 1, 2026 - Aug 20, 2026",
    startDate: "2026-06-01",
    endDate: "2026-08-20",
    term: "summer",
    features: ["communication", "maintenance", "cheap"],
    price: 740,
    monthlyRent: 740,
    priceUnit: "per month",
    desc: "One room open in a friendly 3-person bungalow near the North Loop shops and coffee. Flexible move-in/move-out within the window. Central AC, fenced yard, and street parking. Short bus ride up Guadalupe to campus.",
    postedBy: "Jordan Lee",
    posterEmail: "jordan.demo@example.com",
    phone: "(512) 555-0198",
    photos: [img("ch-northloop-bungalow-a")],
    ownerUid: "demo-jordan",
    posterUsername: "jordanlee",
    status: "approved",
    underReview: false,
    demo: true,
  },
  {
    id: "demo-2026-eastcampus-loft",
    title: "Modern Loft Room Steps from East Campus",
    location: "East Campus, Austin",
    address: "2318 Leon St, Austin, TX 78705",
    dates: "Aug 15, 2026 - Dec 15, 2026",
    startDate: "2026-08-15",
    endDate: "2026-12-15",
    term: "winter",
    features: ["cleanliness", "security", "maintenance"],
    price: 895,
    monthlyRent: 895,
    priceUnit: "per month",
    desc: "Room in a modern two-story loft a five-minute walk to the east side of campus and the stadium. Stainless kitchen, in-unit laundry, and a covered parking spot. Subletting for the fall while I co-op out of state.",
    postedBy: "Alex Nguyen",
    posterEmail: "alex.demo@example.com",
    phone: "(512) 555-0173",
    photos: [img("ch-eastcampus-loft-a")],
    ownerUid: "demo-alex",
    posterUsername: "alexnguyen",
    status: "approved",
    underReview: false,
    demo: true,
  },
  {
    id: "demo-2027-farwest-apartment",
    title: "Sunny 1BR on the Far West Shuttle Route",
    location: "Far West, Austin",
    address: "3600 Greystone Dr, Austin, TX 78731",
    dates: "Jan 10, 2027 - May 15, 2027",
    startDate: "2027-01-10",
    endDate: "2027-05-15",
    term: "winter",
    features: ["cheap", "communication", "cleanliness"],
    price: 860,
    monthlyRent: 860,
    priceUnit: "per month",
    desc: "Whole one-bedroom on the Far West shuttle line, subletting for spring while I'm on an exchange. Quiet complex with a pool and covered parking, big closets, and a balcony. Easy 15-minute ride to campus.",
    postedBy: "Sofia Ramirez",
    posterEmail: "sofia.demo@example.com",
    phone: "(512) 555-0164",
    photos: [img("ch-farwest-apartment-a")],
    ownerUid: "demo-sofia",
    posterUsername: "sofiaramirez",
    status: "approved",
    underReview: false,
    demo: true,
  },
];

export function mergeDemoListings(listings) {
  const seen = new Set(listings.map((listing) => listing.id));
  return [...listings, ...DEMO_LISTINGS.filter((listing) => !seen.has(listing.id))];
}

export function findDemoListing(id) {
  return DEMO_LISTINGS.find((listing) => String(listing.id) === String(id));
}
